version = '0.0.0'

[[files."CHANGELOG.rst"]]
search = """
`Unreleased`_
+++++++++++++
"""


replace = """
`Unreleased`_
+++++++++++++

`{{new_version}}`_ - {{utcnow | strftime('%Y-%m-%d')}}
++++++++++++++++++++++
"""

[[files."CHANGELOG.rst"]]
search = """
.. _`Unreleased`: https://github.com/okchaty/terraform-module-aws-s3-redirect/compare/{{old_version}}...HEAD
"""
replace = """
.. _`Unreleased`: https://github.com/okchaty/terraform-module-aws-s3-redirect/compare/{{new_version}}...HEAD
.. _{{new_version}}: https://github.com/okchaty/terraform-module-aws-s3-redirect/compare/{{old_version}}...{{new_version}}
"""
